name: CI/CD para SEVD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Levantar entorno con Docker
      run: |
        docker-compose up -d
        sleep 5

    - name: Probar si anda el sistema
      run: |
        curl -I http://localhost:8080 | grep "200 OK"
